name: Auto commit
on: workflow_dispatch
jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: date +%s > file.txt
      - name: Commit file
        run: |
          git config --global user.name 'unoduequattro'
          git config --global user.email 'unoduequattro@users.noreply.github.com'
          git commit -am "Auto commit"
          git push
