name: Auto commit
on:
  schedule:
    - cron:  '25 14 * * 4'
jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create file
        run: echo "link=www.semrush.com\nkey=shakalaka+$(date +%s)" > file.txt
      - name: Commit file
        run: |
          git config --global user.name 'unoduequattro'
          git config --global user.email 'unoduequattro@users.noreply.github.com'
          git commit -am "Auto commit"
          git push
